spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 34117ea0d2791ede610f
            client-secret: f7171714c0799fda68e92689f80ab63a7e2540aa

logging:
  level:
    org:
      springframework: DEBUG
      springframework.security: DEBUG


#spring.security.oauth2.client.registration.github.client-id = 3e23a2c6d4dfda3443b4
#spring.security.oauth2.client.registration.github.client-secret = a12a23d213319bbb88bf620ea92569bbb0ccb381
#logging.level.org.springframework.security=DEBUG
#logging.level.org.springframework = DEBUG
